# Configuration file for CoinSystem
# CoinSystem by @McpeBooster and @StuckDexter

#If you need help, look at the ReadMe.md


#Every change needs an Server Restart!


#Language of the Plugin: only supportet eng
language: eng