# Configuration file for CoinSystem
# CoinSystem by @McpeBooster and @StuckDexter

#If you need help, look at the ReadMe.md


#Every change needs an Server Restart!


#Language of the Plugin: only supportet eng
language: eng

#Choose which type of Provider you want to use: only supported mysql, sqlite3
provider: sqlite3

#MySQl Connection Options
mysql:
    host: "example.net:3306"
    username: "YourUser"
    password: "password123"
    database: "CoinSystem"

#SQlite3 Connection Options
sqlite3:
    path: "/home"